sudo: required
services:
  - docker

before_install:
  - docker build -t pupinia/docker-react -f Dockerfile.dev .

script:
  - docker run pupinia/docker-react npm run test -- --coverage --watchAll=false
